version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  ui:
    build:
      context: .
      dockerfile: dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api